name: CustomsTnTFill
version: ${project.version}
main: CustomsTnTFill.CustomsTnTFillPlugin
description: A tntfill plugin !
author: CustomEnchants
commands:
  tntfill:
     aliases: [etntfill]
     description: Fill Dispensers with TnT